version: "3"
services:
  job-searcher-api:
    build:
      context: ./job-searcher
      dockerfile: Dockerfile
    container_name: "job-searcher-api"
    ports:
      - 3000:3000
  web-app:
    build:
      context: ./web-app
      dockerfile: Dockerfile
    container_name: "web-app"
    ports:
      - 8080:8080
